# Generated by Django 5.1.7 on 2025-10-29 08:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('WIRE', 'Wire Transfer'), ('ATM', 'ATM Transaction'), ('CHECK', 'Check'), ('CARD', 'Card Payment'), ('CRYPTO', 'Cryptocurrency'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('originating_country', models.CharField(blank=True, max_length=100)),
                ('destination_country', models.CharField(blank=True, max_length=100)),
                ('sender_account', models.CharField(blank=True, max_length=100)),
                ('receiver_account', models.CharField(blank=True, max_length=100)),
                ('sender_bank', models.CharField(blank=True, max_length=200)),
                ('receiver_bank', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('FLAGGED', 'Flagged for Review'), ('UNDER_REVIEW', 'Under Review'), ('CLEARED', 'Cleared'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20)),
                ('transaction_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('velocity_flag', models.BooleanField(default=False)),
                ('structuring_flag', models.BooleanField(default=False)),
                ('unusual_pattern_flag', models.BooleanField(default=False)),
                ('high_risk_country_flag', models.BooleanField(default=False)),
                ('amount_threshold_flag', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=200)),
                ('channel', models.CharField(blank=True, max_length=50)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='accounts.customer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='accounts.customer')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['transaction_id'], name='transaction_transac_5011c8_idx'), models.Index(fields=['sender', 'transaction_date'], name='transaction_sender__d92ebc_idx'), models.Index(fields=['receiver', 'transaction_date'], name='transaction_receive_6fbfb9_idx'), models.Index(fields=['status'], name='transaction_status_505a2f_idx'), models.Index(fields=['is_suspicious'], name='transaction_is_susp_f63ecc_idx'), models.Index(fields=['transaction_date'], name='transaction_transac_0d716a_idx'), models.Index(fields=['amount'], name='transaction_amount_8c918e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_transaction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_transaction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction_count_daily', models.IntegerField(default=0)),
                ('transaction_count_weekly', models.IntegerField(default=0)),
                ('transaction_count_monthly', models.IntegerField(default=0)),
                ('common_countries', models.JSONField(default=list)),
                ('common_transaction_types', models.JSONField(default=list)),
                ('typical_transaction_times', models.JSONField(default=list)),
                ('sudden_increase_flag', models.BooleanField(default=False)),
                ('dormant_account_activity', models.BooleanField(default=False)),
                ('cross_border_frequency', models.IntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='accounts.customer')),
            ],
            options={
                'verbose_name': 'Transaction Pattern',
                'verbose_name_plural': 'Transaction Patterns',
                'db_table': 'transaction_patterns',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['customer', 'period_end'], name='transaction_custome_43722f_idx')],
            },
        ),
    ]
