from rest_framework import serializers
from .models import Customer


class CustomerSerializer(serializers.ModelSerializer):
    """Serializer for Customer model"""
    assigned_analyst_username = serializers.CharField(source='assigned_analyst.username', read_only=True)
    
    class Meta:
        model = Customer
        fields = [
            'id', 'customer_id', 'customer_type', 'first_name', 'last_name',
            'date_of_birth', 'company_name', 'registration_number',
            'email', 'phone_number', 'address', 'city', 'country', 'postal_code',
            'risk_level', 'risk_score', 'is_pep', 'pep_details',
            'is_sanctioned', 'sanction_details', 'kyc_verified',
            'kyc_verification_date', 'kyc_document_type',
            'created_at', 'updated_at', 'is_active',
            'assigned_analyst', 'assigned_analyst_username'
        ]
        read_only_fields = ['id', 'created_at', 'updated_at', 'risk_score']


class CustomerCreateSerializer(serializers.ModelSerializer):
    """Serializer for creating Customer"""
    
    class Meta:
        model = Customer
        fields = [
            'customer_id', 'customer_type', 'first_name', 'last_name',
            'date_of_birth', 'company_name', 'registration_number',
            'email', 'phone_number', 'address', 'city', 'country', 'postal_code',
            'risk_level', 'is_pep', 'pep_details',
            'is_sanctioned', 'sanction_details', 'kyc_verified',
            'kyc_document_type', 'assigned_analyst'
        ]
        read_only_fields = ['customer_id', 'risk_level']  # Auto-generated by system
    
    def validate(self, data):
        """
        Ensure kyc_verified is False when creating (KYC will be done separately)
        """
        # Force kyc_verified to False - KYC will be completed through the KYC workflow
        data['kyc_verified'] = False
        return data


