# Generated by Django 5.1.7 on 2025-11-18 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=50)),
                ('customer_type', models.CharField(max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('risk_level', models.CharField(default='LOW', max_length=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('is_pep', models.BooleanField(default=False)),
                ('pep_details', models.TextField(blank=True)),
                ('is_sanctioned', models.BooleanField(default=False)),
                ('sanction_details', models.TextField(blank=True)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('kyc_verification_date', models.DateTimeField(blank=True, null=True)),
                ('kyc_document_type', models.CharField(blank=True, max_length=100)),
                ('original_id', models.IntegerField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deleted Customer',
                'verbose_name_plural': 'Deleted Customers',
                'db_table': 'deleted_customers',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['customer_id'], name='deleted_cus_custome_49b9ae_idx'), models.Index(fields=['deleted_at'], name='deleted_cus_deleted_e094c6_idx')],
            },
        ),
    ]
