# Generated by Django 5.1.7 on 2025-11-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_deletedcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('ANALYST', 'Compliance Analyst'), ('INVESTIGATOR', 'Investigator'), ('VIEWER', 'Viewer'), ('REGULATOR', 'Regulator'), ('BANK', 'Bank User')], default='VIEWER', max_length=20),
        ),
    ]
