# Generated by Django 5.1.7 on 2025-10-29 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('alert_type', models.CharField(choices=[('THRESHOLD', 'Threshold Breach'), ('STRUCTURING', 'Structuring/Smurfing'), ('VELOCITY', 'High Velocity'), ('UNUSUAL_PATTERN', 'Unusual Pattern'), ('PEP', 'PEP Transaction'), ('SANCTION', 'Sanctions Match'), ('HIGH_RISK_COUNTRY', 'High Risk Country'), ('LARGE_CASH', 'Large Cash Transaction'), ('ROUND_AMOUNT', 'Round Amount'), ('RAPID_MOVEMENT', 'Rapid Fund Movement'), ('ML_PREDICTION', 'ML Model Prediction'), ('OTHER', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive'), ('SAR_FILED', 'SAR Filed'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('risk_score', models.FloatField(default=0.0)),
                ('ml_confidence', models.FloatField(default=0.0)),
                ('ml_features', models.JSONField(default=dict)),
                ('priority', models.IntegerField(default=3)),
                ('investigation_notes', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.customer')),
                ('transactions', models.ManyToManyField(blank=True, related_name='alerts', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rule_type', models.CharField(choices=[('THRESHOLD', 'Threshold Breach'), ('STRUCTURING', 'Structuring/Smurfing'), ('VELOCITY', 'High Velocity'), ('UNUSUAL_PATTERN', 'Unusual Pattern'), ('PEP', 'PEP Transaction'), ('SANCTION', 'Sanctions Match'), ('HIGH_RISK_COUNTRY', 'High Risk Country'), ('LARGE_CASH', 'Large Cash Transaction'), ('ROUND_AMOUNT', 'Round Amount'), ('RAPID_MOVEMENT', 'Rapid Fund Movement'), ('ML_PREDICTION', 'ML Model Prediction'), ('OTHER', 'Other')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('threshold_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'db_table': 'alert_rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('findings', models.TextField()),
                ('evidence_collected', models.JSONField(default=list)),
                ('initial_risk_score', models.FloatField()),
                ('final_risk_score', models.FloatField(blank=True, null=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('recommendation', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('sar_required', models.BooleanField(default=False)),
                ('sar_filed', models.BooleanField(default=False)),
                ('sar_filing_date', models.DateTimeField(blank=True, null=True)),
                ('sar_reference', models.CharField(blank=True, max_length=100)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation', to='alerts.alert')),
                ('investigator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_alerts', models.ManyToManyField(blank=True, related_name='related_investigations', to='alerts.alert')),
            ],
            options={
                'verbose_name': 'Investigation',
                'verbose_name_plural': 'Investigations',
                'db_table': 'investigations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_id'], name='alerts_alert_i_d3be29_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['customer', 'status'], name='alerts_custome_ee8cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'severity'], name='alerts_status_5203b6_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['assigned_to', 'status'], name='alerts_assigne_ef25da_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['triggered_at'], name='alerts_trigger_bbc1f5_idx'),
        ),
    ]
