# Generated by Django 5.1.7 on 2025-10-29 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('TRANSACTION_RISK', 'Transaction Risk Scoring'), ('CUSTOMER_RISK', 'Customer Risk Profiling'), ('ANOMALY_DETECTION', 'Anomaly Detection'), ('PATTERN_RECOGNITION', 'Pattern Recognition'), ('NETWORK_ANALYSIS', 'Network Analysis')], max_length=30)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('TRAINING', 'Training'), ('TESTING', 'Testing'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='TRAINING', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('algorithm', models.CharField(max_length=100)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('auc_roc', models.FloatField(blank=True, null=True)),
                ('training_data_size', models.IntegerField(default=0)),
                ('features_used', models.JSONField(default=list)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('model_file_path', models.CharField(blank=True, max_length=500)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'db_table': 'ml_models',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fraudulent', models.BooleanField()),
                ('is_suspicious', models.BooleanField()),
                ('features', models.JSONField(default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=100)),
                ('labeled_at', models.DateTimeField(auto_now_add=True)),
                ('used_in_training', models.BooleanField(default=False)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Training Data',
                'verbose_name_plural': 'Training Data',
                'db_table': 'training_data',
                'ordering': ['-labeled_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_score', models.FloatField()),
                ('anomaly_type', models.CharField(max_length=100)),
                ('detection_method', models.CharField(max_length=100)),
                ('baseline_pattern', models.JSONField(default=dict)),
                ('deviation_details', models.JSONField(default=dict)),
                ('reviewed', models.BooleanField(default=False)),
                ('is_confirmed_anomaly', models.BooleanField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='accounts.customer')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='transactions.transaction')),
                ('ml_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_engine.mlmodel')),
            ],
            options={
                'verbose_name': 'Anomaly Detection',
                'verbose_name_plural': 'Anomaly Detections',
                'db_table': 'anomaly_detections',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['customer', 'detected_at'], name='anomaly_det_custome_5b6427_idx'), models.Index(fields=['reviewed'], name='anomaly_det_reviewe_193a16_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_suspicious', models.BooleanField()),
                ('suspicion_score', models.FloatField()),
                ('prediction_class', models.CharField(blank=True, max_length=50)),
                ('feature_importance', models.JSONField(default=dict)),
                ('raw_prediction', models.JSONField(default=dict)),
                ('actual_outcome', models.BooleanField(blank=True, null=True)),
                ('feedback_provided', models.BooleanField(default=False)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_engine.mlmodel')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Model Prediction',
                'verbose_name_plural': 'Model Predictions',
                'db_table': 'model_predictions',
                'ordering': ['-predicted_at'],
                'indexes': [models.Index(fields=['transaction', 'ml_model'], name='model_predi_transac_fc8457_idx'), models.Index(fields=['is_suspicious'], name='model_predi_is_susp_2944aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('TRANSACTION', 'Transaction')], max_length=20)),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('risk_factors', models.JSONField(default=dict)),
                ('feature_values', models.JSONField(default=dict)),
                ('explanation', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='accounts.customer')),
                ('ml_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_scores', to='ml_engine.mlmodel')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Risk Score',
                'verbose_name_plural': 'Risk Scores',
                'db_table': 'risk_scores',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['customer', 'calculated_at'], name='risk_scores_custome_92e00a_idx'), models.Index(fields=['transaction', 'calculated_at'], name='risk_scores_transac_a154ad_idx'), models.Index(fields=['risk_level'], name='risk_scores_risk_le_94baf8_idx')],
            },
        ),
    ]
